Repository angular/angular-ja, pull requests merged in 2018-07, with the labels that each got.

#204 translate guide/singleton-service
  aio-ja/content/guide/singleton-services.en.md
  aio-ja/content/guide/singleton-services.md
Labels: pr_state: Wait for merging, type: translation

#199 translate guide/providers.md
  aio-ja/content/guide/providers.en.md
  aio-ja/content/guide/providers.md
Labels: pr_state: Need to fix, type: translation

#206 Fix typo in toh-pt4.md
  aio-ja/content/tutorial/toh-pt4.md
Labels: pr_state: Wait for merging

#196 Guide/component styles
  aio-ja/content/guide/component-styles.en.md
  aio-ja/content/guide/component-styles.md
Labels: pr_state: Need to fix, type: translation

#197 Translate guide/security
  aio-ja/content/guide/security.en.md
  aio-ja/content/guide/security.md
Labels: pr_state: Wait for merging, type: translation

#202 translate: guide/observablesを翻訳
  aio-ja/content/guide/observables.en.md
  aio-ja/content/guide/observables.md
Labels: pr_state: Wait for merging, type: translation

#189 translate: guide/dynamic-form.md
  aio-ja/content/guide/dynamic-form.en.md
  aio-ja/content/guide/dynamic-form.md
Labels: pr_state: Wait for merging, type: translation

#208 translate guide/lazy-loading-ngmodules.md
  aio-ja/content/guide/lazy-loading-ngmodules.en.md
  aio-ja/content/guide/lazy-loading-ngmodules.md
Labels: pr_state: Need to fix, type: translation

#213 guide/ngmodule-api.md の翻訳
  aio-ja/content/guide/ngmodule-api.en.md
  aio-ja/content/guide/ngmodule-api.md
Labels: pr_state: Wait for merging, type: translation
