Repository angular/angular-ja, pull requests merged in 2018-09, with the labels that each got.

#232 Update events.html
  aio-ja/content/marketing/events.html
Labels: pr_state: Wait for merging

#225 guide/typescript-configurationの翻訳
  aio-ja/content/guide/typescript-configuration.en.md
  aio-ja/content/guide/typescript-configuration.md
Labels: pr_state: Wait for merging, type: translation

#228 translate guide/architecture-components.md
  aio-ja/content/guide/architecture-components.en.md
  aio-ja/content/guide/architecture-components.md
Labels: pr_state: Wait for merging, type: translation

#234 fixed: clear unnecessary string
  aio-ja/content/guide/architecture-components.md
Labels: pr_state: Wait for merging

#235 Translate/architecture services.md
  aio-ja/content/guide/architecture-next-steps.en.md
  aio-ja/content/guide/architecture-next-steps.md
  aio-ja/content/guide/architecture-services.en.md
  aio-ja/content/guide/architecture-services.md
Labels: pr_state: Wait for merging, type: translation

#237 Feature/217 reactive form
  aio-ja/content/guide/reactive-forms.en.md
  aio-ja/content/guide/reactive-forms.md
  aio-ja/content/guide/reactive-forms.md.old
Labels: pr_state: Wait for merging, type: translation

#239 translate guide/rx-library
  aio-ja/content/guide/rx-library.en.md
  aio-ja/content/guide/rx-library.md
Labels: pr_state: Need to fix, type: translation

#231 guide/form-validation.mdの翻訳
  aio-ja/content/guide/form-validation.md
Labels: pr_state: Wait for merging, type: translation
