Repository angular/angular-ja, pull requests merged in 2018-11, with the labels that each got.

#260 translate guide/transition-and-triggers
  aio-ja/content/guide/transition-and-triggers.en.md
  aio-ja/content/guide/transition-and-triggers.md
Labels: pr_state: Wait for review, type: translation

#264 translate: guide/reusable-animations.md (#263)
  aio-ja/content/guide/reusable-animations.en.md
  aio-ja/content/guide/reusable-animations.md
Labels: pr_state: Wait for merging, type: translation

#262 translate: guide/complex-animation-sequences.md (#261)
  aio-ja/content/guide/complex-animation-sequences.en.md
  aio-ja/content/guide/complex-animation-sequences.md
Labels: pr_state: Wait for merging, pr_state: Wait for review, type: translation

#267 fix typo 絶体 -> 絶対
  aio-ja/content/guide/http.md
  aio-ja/content/guide/http.old.md
Labels: pr_state: Wait for merging, type: translation
