Repository angular/angular-ja, pull requests merged in 2019-03, with the labels that each got.

#305 translate: guide/dependency-injection-in-action.mdの翻訳
  aio-ja/content/guide/dependency-injection-in-action.en.md
  aio-ja/content/guide/dependency-injection-in-action.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#315 [styleguide] 命名規則の翻訳 # Pipe names
  aio-ja/content/guide/styleguide.md
Labels: cla: yes

#317 chore: styleguideの見出しを翻訳
  aio-ja/content/guide/styleguide.md
  aio-ja/content/navigation.json
Labels: cla: yes

#318 fix: http.mdを微修正
  aio-ja/content/guide/http.md
Labels: cla: yes

#310 guide/workspace-config の翻訳
  aio-ja/content/guide/workspace-config.en.md
  aio-ja/content/guide/workspace-config.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Wait for merging, type: translation

#319 [styleguide] 命名規則の翻訳 # unit test file names
  aio-ja/content/guide/styleguide.md
Labels: cla: yes

#320 [styleguide] naming convention for directives (#308)
  aio-ja/content/guide/styleguide.md
Labels: cla: yes

#313 guide/routerの翻訳 (OverviewとThe Basics) refs #203
  aio-ja/content/guide/router.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review, type: translation

#314 translate: guide/build の翻訳
  aio-ja/content/guide/build.en.md
  aio-ja/content/guide/build.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review, type: translation

#322 translatre: styleguide coding conventionsの翻訳
  aio-ja/content/guide/styleguide.md
Labels: cla: yes

#324 translate: styleguide Service - Appendixの翻訳
  aio-ja/content/guide/styleguide.md
Labels: cla: yes

#326 translate: styleguide Components - Directivesの翻訳
  aio-ja/content/guide/styleguide.md
Labels: cla: yes

#329 translate: styleguide namingの残りを翻訳
  aio-ja/content/guide/styleguide.md
Labels: cla: yes

#330 guide/routerの翻訳 (オリジナルのenファイルを追加) refs #203
  aio-ja/content/guide/router.en.md
Labels: cla: yes

#333 fix: プレフィックス、サフィックスについてのルールを追加
  aio-ja/content/guide/architecture-modules.md
  aio-ja/content/guide/attribute-directives.md
  aio-ja/content/guide/build.md
  aio-ja/content/guide/feature-modules.md
  aio-ja/content/guide/security.md
  aio-ja/content/guide/service-worker-config.md
  aio-ja/content/guide/styleguide.md
  prh.yml
Labels: cla: yes

#331 Fix a little about routing and styleguide
  aio-ja/content/guide/router.md
  aio-ja/content/guide/styleguide.md
  aio-ja/content/navigation.json
Labels: cla: yes

#335 fix: quickstart.mdを微修正
  aio-ja/content/guide/quickstart.md
Labels: cla: yes

#336 Update events.html
  aio-ja/content/marketing/events.html
Labels: cla: yes

#338 fix: typo testing.md
  aio-ja/content/guide/testing.md
Labels: cla: yes

#339 fix: typo setup.md
  aio-ja/content/guide/setup.md
Labels: cla: yes
