Repository angular/angular-ja, pull requests merged in 2019-05, with the labels that each got.

#316 translate: guide/dependency-injection-navtree.md
  aio-ja/content/guide/dependency-injection-navtree.md
Labels: cla: yes, pr_state: Wait for merging, pr_state: Wait for review, type: translation

#352 translate: guide/dependency-injection-navtree.md
  aio-ja/content/guide/dependency-injection-navtree.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#356 fix: typo tutorial/toh-pt2.md
  aio-ja/content/tutorial/toh-pt2.md
Labels: cla: yes

#354 translate: guide/libraries
  aio-ja/content/guide/libraries.en.md
  aio-ja/content/guide/libraries.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#358 translate: guide/template-syntax.md の翻訳(Built-in structural directives 前まで)
  aio-ja/content/guide/template-syntax.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#360 chore: change of wording tutorial/toh-pt2.md
  aio-ja/content/tutorial/toh-pt2.md
Labels: cla: no, pr_state: Wait for merging

#357 translate: guide/set-document-title
  aio-ja/content/guide/set-document-title.en.md
  aio-ja/content/guide/set-document-title.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#359 translate guide/using-libraries
  aio-ja/content/guide/using-libraries.en.md
  aio-ja/content/guide/using-libraries.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#361 guide/template-syntax.md の翻訳(最後まで)
  aio-ja/content/guide/template-syntax.md
Labels: cla: yes, pr_state: Wait for merging, pr_state: Wait for review
