Repository angular/angular-ja, pull requests merged in 2019-06, with the labels that each got.

#372 chore: update docs for contributors
  CONTRIBUTING.md
  CONTRIBUTION.md
  README.md
  docs/edit-on-github.png
Labels: cla: yes

#382 fix: "start working" の翻訳を修正
  aio-ja/content/marketing/docs.md
Labels: cla: yes

#383 translate: start/index.md (#373)
  aio-ja/content/start/index.en.md
  aio-ja/content/start/index.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review

#365 translate guide/i18n
  aio-ja/content/guide/i18n.en.md
  aio-ja/content/guide/i18n.md
Labels: cla: no, pr_state: Need to fix, pr_state: Wait for review

#385 translate: cli/index.md
  aio-ja/content/cli/index.en.md
  aio-ja/content/cli/index.md
Labels: cla: yes, pr_state: Wait for merging, pr_state: Wait for review

#390 translate: guide/releasesの追加翻訳
  aio-ja/content/guide/releases.md
Labels: cla: yes

#386 guide/singleton-services の翻訳
  aio-ja/content/guide/singleton-services.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review

#392 translate: start/forms.md
  aio-ja/content/start/forms.en.md
  aio-ja/content/start/forms.md
Labels: cla: yes, pr_state: Wait for merging

#384 translate: start/routing #374
  aio-ja/content/start/routing.en.md
  aio-ja/content/start/routing.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review

#394 translate: start/deployment.md
  aio-ja/content/start/deployment.en.md
  aio-ja/content/start/deployment.md
Labels: cla: yes, pr_state: Wait for merging

#396 translate: guide/structural-directives
  aio-ja/content/guide/structural-directives.en.md
  aio-ja/content/guide/structural-directives.md
Labels: cla: yes, pr_state: Wait for merging

#399 Fix guide/structural directive
  aio-ja/content/guide/structural-directives.md
Labels: cla: yes

#401 translate: guide/setup-localの翻訳
  aio-ja/content/cli/index.md
  aio-ja/content/guide/setup-local.en.md
  aio-ja/content/guide/setup-local.md
  aio-ja/content/guide/setup.md
  aio-ja/content/guide/using-libraries.md
  prh.yml
Labels: cla: yes

#397 translate: start/data.md
  aio-ja/content/start/data.en.md
  aio-ja/content/start/data.md
Labels: cla: no, pr_state: Wait for review

#362 translate creating-libraries.md
  aio-ja/content/guide/creating-libraries.en.md
  aio-ja/content/guide/creating-libraries.md
Labels: cla: yes, pr_state: Wait for merging

#391 translate: cli/usage-analytics-gathering.md
  aio-ja/content/cli/usage-analytics-gathering.en.md
  aio-ja/content/cli/usage-analytics-gathering.md
Labels: cla: yes, pr_state: Wait for merging

#393 chore: lint構成を刷新
  .textlintrc
  package.json
  prh.yml
  test/techbooster.yml
  yarn.lock
Labels: cla: yes

#402 fix: typo start/index.md
  aio-ja/content/start/index.md
Labels: cla: yes, pr_state: Wait for merging

#405 chore: fix ci apt-get
  .circleci/config.yml
Labels: cla: yes

#404 translate: guide/file-structure
  aio-ja/content/guide/file-structure.md
Labels: cla: yes, pr_state: Need to fix

#403 translate guide/app-shell
  aio-ja/content/guide/app-shell.en.md
  aio-ja/content/guide/app-shell.md
Labels: cla: no, pr_state: Wait for merging

#406 translate: guide/workspace-config.md
  aio-ja/content/guide/workspace-config.md
Labels: cla: yes, pr_state: Wait for merging
