Repository angular/angular-ja, pull requests merged in 2019-12, with the labels that each got.

#465 fix: guide/http.md: 原文更新部分を翻訳
  aio-ja/content/guide/http.md
Labels: cla: yes, pr_state: Need to fix, type: translation

#463 translate: guide/upgrade
  aio-ja/content/guide/upgrade.en.md
  aio-ja/content/guide/upgrade.md
Labels: cla: yes, pr_state: Wait for review, type: translation

#471 fix: start/forms: 軽微な修正
  aio-ja/content/start/forms.md
Labels: cla: yes, pr_state: Ready to Merge, type: translation
