Repository angular/angular-ja, pull requests merged in 2019-08, with the labels that each got.

#416 軽微な修正: guide/architecture.md
  aio-ja/content/guide/architecture.md
Labels: cla: yes, pr_state: Wait for merging

#418 軽微な修正: guide/architecture-components.md
  aio-ja/content/guide/architecture-components.md
Labels: cla: yes, pr_state: Wait for merging, pr_state: Wait for review

#417 軽微な修正: guide/architecture-modules.md
  aio-ja/content/guide/architecture-modules.md
Labels: cla: yes, pr_state: Wait for merging, pr_state: Wait for review

#420 軽微な修正: guide/architecture-services.md
  aio-ja/content/guide/architecture-services.md
Labels: cla: yes, pr_state: Wait for merging

#407 Translate/aot-compiler
  aio-ja/content/guide/aot-compiler.md
Labels: cla: yes, pr_state: Need to fix

#424 軽微な修正: guide/service-worker-devops.md
  aio-ja/content/guide/service-worker-devops.md
Labels: cla: yes, pr_state: Wait for merging

#423 Translate ivy into japanese.
  aio-ja/content/guide/ivy.en.md
  aio-ja/content/guide/ivy.md
Labels: cla: yes, pr_state: Wait for merging

#422 Translate web-worker into japanese.
  aio-ja/content/guide/web-worker.en.md
  aio-ja/content/guide/web-worker.md
Labels: cla: yes, pr_state: Wait for merging

#430 軽微な修正: guide/ngmodule-vs-jsmodule.md: 原文更新により
  aio-ja/content/guide/ngmodule-vs-jsmodule.md
Labels: cla: yes, pr_state: Wait for merging

#431 軽微な修正: guide/frequent-ngmodules.md: 原文更新により
  aio-ja/content/guide/frequent-ngmodules.md
Labels: cla: yes, pr_state: Wait for merging

#433 軽微な修正: guide/module-types.md:
  aio-ja/content/guide/module-types.md
Labels: cla: yes

#435 軽微な修正: guide/feature-modules.md:
  aio-ja/content/guide/feature-modules.md
Labels: cla: yes

#434 超軽微な修正: guide/entry-components.md:
  aio-ja/content/guide/entry-components.md
Labels: cla: yes

#436 軽微な修正: guide/providers.md
  aio-ja/content/guide/providers.md
Labels: cla: yes

#439 fix: guide/aot-compiler.md: 軽微な修正
  aio-ja/content/guide/aot-compiler.md
Labels: cla: yes, pr_state: Wait for merging

#443 イベントを新しいものから並べるようにしました
  aio-ja/content/marketing/events.html
Labels: cla: yes

#440 fix: guide/aot-compiler: 軽微な修正
  aio-ja/content/guide/aot-compiler.md
Labels: cla: yes, pr_state: Wait for merging

#445 軽微な修正: guide/singleton-services.md
  aio-ja/content/guide/singleton-services.md
Labels: cla: yes

#432 Translate/angular compiler options
  aio-ja/content/guide/angular-compiler-options.en.md
  aio-ja/content/guide/angular-compiler-options.md
Labels: cla: yes, pr_state: Need to fix

#428 Translate/dependency injection providers
  aio-ja/content/guide/dependency-injection-providers.en.md
  aio-ja/content/guide/dependency-injection-providers.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#446 translate: guide/accessibility
  aio-ja/content/guide/accessibility.en.md
  aio-ja/content/guide/accessibility.md
Labels: cla: yes, pr_state: Wait for merging

#449 軽微な修正: guide/lazy-loading-ngmodules.md
  aio-ja/content/guide/lazy-loading-ngmodules.md
Labels: cla: yes, pr_state: Wait for merging

#448 軽微な修正: guide/entry-components.md
  aio-ja/content/guide/entry-components.md
Labels: cla: yes, pr_state: Wait for merging

#450 軽微な修正: guide/sharing-ngmodules.md
  aio-ja/content/guide/sharing-ngmodules.md
Labels: cla: yes, pr_state: Wait for merging

#453 docs(events): イベントを追加
  aio-ja/content/marketing/events.html
Labels: cla: yes

#452 fix: guide/architecture-components: 軽微な修正
  aio-ja/content/guide/architecture-components.md
Labels: cla: yes

#455 fix: guide/build: 軽微な修正
  aio-ja/content/guide/build.md
Labels: cla: yes

#451 軽微な修正: guide/ngmodule-api.md
  aio-ja/content/guide/ngmodule-api.md
Labels: cla: yes, pr_state: Wait for merging
