Repository angular/angular-ja, pull requests merged in 2019-02, with the labels that each got.

#289 Add space before and after backquote and so on
  aio-ja/content/guide/forms.md
Labels: pr_state: Wait for merging, type: translation

#288 refs #286 translation for file-structure
  aio-ja/content/guide/file-structure.en.md
  aio-ja/content/guide/file-structure.md
  aio-ja/content/navigation.json
Labels: pr_state: Wait for merging, type: translation

#306 Pipesの冒頭と、Chaining pipesのくだりの日本語表現を改善しました
  aio-ja/content/guide/pipes.md
Labels: cla: no, pr_state: Need to fix, type: translation

#309 Noto Sans JPを利用する
  aio-ja/src/index.html
  aio-ja/src/styles/_constants.scss
Labels: cla: yes

#312 chore: use contributors-img
  README.md
Labels: cla: yes
