Repository angular/angular-ja, pull requests merged in 2019-04, with the labels that each got.

#340 Fix/toh-pt3
  aio-ja/content/tutorial/toh-pt3.md
Labels: cla: yes, pr_state: Wait for merging

#343 改行を追加しました
  aio-ja/content/guide/testing.md
Labels: cla: yes

#341 translate: tutorial/toh-pt5.md 未翻訳の注記部分を翻訳
  aio-ja/content/tutorial/toh-pt5.md
Labels: cla: yes, pr_state: Wait for merging

#337 translate: guide/npm-packages.md
  aio-ja/content/guide/npm-packages.en.md
  aio-ja/content/guide/npm-packages.md
Labels: cla: yes, pr_state: Wait for merging, type: translation

#347 guide/observables.md の翻訳
  aio-ja/content/guide/observables.md
Labels: cla: yes
