Repository angular/angular-ja, pull requests merged in 2019-07, with the labels that each got.

#411 軽微な修正: guide/dependency-injection.md
  aio-ja/content/guide/dependency-injection.md
Labels: cla: yes

#413 guide/bazel の翻訳 #412
  aio-ja/content/guide/bazel.en.md
  aio-ja/content/guide/bazel.md
  aio-ja/content/guide/releases.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Wait for merging, type: translation

#415 超軽微な修正: guide/bootstrapping.md
  aio-ja/content/guide/bootstrapping.md
Labels: cla: yes, pr_state: Wait for merging

#414 軽微な修正: guide/hierarchical-dependency-injection.md
  aio-ja/content/guide/hierarchical-dependency-injection.md
Labels: cla: yes
