Repository angular/angular-ja, pull requests merged in 2020-07, with the labels that each got.

#541 translate: guide/template-syntax.md の一部
  aio-ja/content/guide/template-syntax.md
Labels: cla: yes, pr_state: Ready to Merge

#544 translate: guide/dynamic-form.md
  aio-ja/content/guide/dynamic-form.en.md
  aio-ja/content/guide/dynamic-form.md
  aio-ja/content/guide/dynamic-form.md.old
Labels: cla: yes, pr_state: Ready to Merge

#547 translate: guide/web-worker.md
  aio-ja/content/guide/web-worker.en.md
  aio-ja/content/guide/web-worker.md
  aio-ja/content/guide/web-worker.md.old
Labels: cla: yes, pr_state: Ready to Merge

#548 translate: guide/schematics (#542)
  aio-ja/content/guide/schematics.en.md
  aio-ja/content/guide/schematics.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Ready to Merge

#555 英語の消し忘れを修正しました。
  aio-ja/content/guide/observables.md
Labels: cla: yes, pr_state: Ready to Merge

#553 translate: /guide/schematics-authoring
  aio-ja/content/guide/schematics-authoring.en.md
  aio-ja/content/guide/schematics-authoring.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Ready to Merge

#556 translate: guide/template-syntax.md の残り
  aio-ja/content/guide/template-syntax.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review

#554 Update router-tutorial.md
  aio-ja/content/guide/router-tutorial.md
Labels: cla: yes, pr_state: Ready to Merge, pr_state: Wait for review

#557 translate: /guide/schematics-for-libraries (#550)
  aio-ja/content/guide/schematics-for-libraries.en.md
  aio-ja/content/guide/schematics-for-libraries.md
Labels: cla: yes, pr_state: Ready to Merge

#560 translate: guide/lifecycle-hooks.md
  aio-ja/content/guide/lifecycle-hooks.en.md
  aio-ja/content/guide/lifecycle-hooks.md
  aio-ja/content/guide/lifecycle-hooks.md.old
Labels: cla: yes, pr_state: Ready to Merge
