Repository angular/angular-ja, pull requests merged in 2020-03, with the labels that each got.

#506 Sync origin e13fcbaa6f
  aio-ja/content/guide/aot-compiler.en.md
  aio-ja/content/guide/aot-compiler.md
  aio-ja/content/guide/architecture-next-steps.en.md
  aio-ja/content/guide/architecture-next-steps.md
  aio-ja/content/guide/deployment.md
  aio-ja/content/guide/displaying-data.en.md
  aio-ja/content/guide/displaying-data.md
  aio-ja/content/guide/releases.en.md
  aio-ja/content/guide/releases.md
  aio-ja/content/guide/router.en.md
  aio-ja/content/guide/router.md
  aio-ja/content/guide/setup-local.en.md
  aio-ja/content/guide/setup-local.md
  aio-ja/content/guide/template-syntax.en.md
  aio-ja/content/guide/template-syntax.md
  aio-ja/content/guide/template-typecheck.md
  aio-ja/content/guide/testing.en.md
  aio-ja/content/guide/testing.md
  aio-ja/content/guide/universal.en.md
  aio-ja/content/guide/universal.md
  aio-ja/content/guide/upgrade.en.md
  aio-ja/content/guide/upgrade.md
  aio-ja/content/guide/zone.md
  aio-ja/content/navigation.en.json
  aio-ja/content/navigation.json
  aio-ja/content/start/deployment.en.md
  aio-ja/content/start/index.en.md
  aio-ja/content/start/index.md
  aio-ja/content/start/start-data.en.md
  aio-ja/content/start/start-data.md
  aio-ja/content/start/start-deployment.en.md
  aio-ja/content/start/start-deployment.md
  aio-ja/content/start/start-forms.en.md
  aio-ja/content/start/start-forms.md
  aio-ja/content/start/start-routing.en.md
  aio-ja/content/start/start-routing.md
  aio-ja/content/tutorial/toh-pt4.en.md
  aio-ja/content/tutorial/toh-pt4.md
  aio-ja/content/tutorial/toh-pt5.en.md
  aio-ja/content/tutorial/toh-pt5.md
  aio-ja/src/index.en.html
  aio-ja/src/index.html
  aio-ja/src/styles/_constants.scss
  update-origin.sh
Labels: cla: yes

#501 translate: guide/ivy.md (#487)
  aio-ja/content/guide/ivy.en.md
  aio-ja/content/guide/ivy.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Wait for review

#507 translate: guide/template-syntax.md の双方向バインディングを翻訳
  aio-ja/content/guide/template-syntax.md
Labels: cla: yes

#508 chore: add netlify badge
  aio-ja/AIO_MODIFY_NOTE.md
  aio-ja/src/app/layout/footer/footer.component.html
  scripts/sync-origin.js
Labels: cla: yes

#511 ci: stop deployment in ci
  .circleci/config.yml
Labels: cla: yes

#509 translate: guide/template-syntax.md のバインディング構文などを翻訳
  aio-ja/content/guide/template-syntax.md
Labels: cla: yes, pr_state: Wait for review

#515 fix: fix typo in tutorial
  aio-ja/content/tutorial/toh-pt5.md
Labels: cla: yes, pr_state: Ready to Merge

#516 ci: make netlify build faster
  build.sh
Labels: cla: yes

#512 ci: Use GitHub Actions for test
  .github/workflows/nodejs.yml
Labels: cla: yes

#514 Translate before 'Universal in action'
  aio-ja/content/guide/universal.md
Labels: cla: yes, pr_state: Need to fix

#517 translate rest part.
  aio-ja/content/guide/angular-compiler-options.md
Labels: cla: yes, pr_state: Ready to Merge

#513 translate: guide/zone.mdの翻訳
  aio-ja/content/guide/zone.en.md
  aio-ja/content/guide/zone.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Ready to Merge

#520 fix: netlifyのSPAフォールバック設定を追加
  .gitignore
  netlify.toml
Labels: cla: yes

#518 translate before 'Configuring builder targets'
  aio-ja/content/guide/workspace-config.md
Labels: cla: yes, pr_state: Ready to Merge, pr_state: Wait for review

#522 translate: guide/template-syntax.md Property binding
  aio-ja/content/guide/template-syntax.md
Labels: cla: yes, pr_state: Ready to Merge

#523 Translate 'displaying-data' into Japanese.
  aio-ja/content/guide/displaying-data.md
Labels: cla: yes, pr_state: Wait for review

#524 ci: clean up CI/CD
  .circleci/config.yml
  .firebaserc
  .github/workflows/build-and-test.yml
  README.md
  firebase.json
  package.json
  yarn.lock
Labels: cla: yes

#526 Translate workspace-config into Japanese.
  aio-ja/content/guide/workspace-config.md
Labels: cla: yes, pr_state: Ready to Merge

#528 translate: guide/architecture-next-steps.md
  aio-ja/content/guide/architecture-next-steps.md
Labels: cla: yes, pr_state: Ready to Merge

#525 translate some part of i18n.
  aio-ja/content/guide/i18n.md
Labels: cla: yes, pr_state: Ready to Merge
