Repository angular/angular-ja, pull requests merged in 2020-11, with the labels that each got.

#583 Update navigation.json
  aio-ja/content/navigation.json
Labels: cla: yes

#587 translate: guide/event-binding-concepts.md
  aio-ja/content/guide/event-binding-concepts.en.md
  aio-ja/content/guide/event-binding-concepts.md
Labels: cla: yes, pr_state: Ready to Merge

#589 軽微な修正: guide/file-structure.md
  aio-ja/content/guide/file-structure.md
Labels: cla: yes

#588 translate: guide/template-reference-variables.md
  aio-ja/content/guide/template-reference-variables.en.md
  aio-ja/content/guide/template-reference-variables.md
Labels: cla: yes, pr_state: Ready to Merge

#590 軽微な修正: guide/typescript-configuration.md
  aio-ja/content/guide/typescript-configuration.md
Labels: cla: yes, pr_state: Ready to Merge

#591 軽微な修正: guide/entry-components.md
  aio-ja/content/guide/entry-components.md
Labels: cla: yes

#596 translate: guide/property-binding-best-practices.md
  aio-ja/content/guide/property-binding-best-practices.en.md
  aio-ja/content/guide/property-binding-best-practices.md
Labels: cla: yes, pr_state: Ready to Merge

#594 translate: guide/strict-mode.md
  aio-ja/content/guide/strict-mode.en.md
  aio-ja/content/guide/strict-mode.md
Labels: cla: yes, pr_state: Wait for review
