Repository angular/angular-ja, pull requests merged in 2020-02, with the labels that each got.

#480 fix: typo in guide/structural-directives.md
  aio-ja/content/guide/structural-directives.md
Labels: cla: yes

#481 Remove duplicate sentences.
  aio-ja/content/tutorial/toh-pt2.md
Labels: cla: yes

#495 translate: /guide/typescript-configuration
  aio-ja/content/guide/typescript-configuration.md
Labels: cla: yes, pr_state: Ready to Merge

#498 translate Language Service guide
  aio-ja/content/guide/language-service.en.md
  aio-ja/content/guide/language-service.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Ready to Merge

#496 translate: guide/lazy-loading-ngmodulesの再翻訳
  aio-ja/content/guide/lazy-loading-ngmodules.md
Labels: cla: yes, pr_state: Need to fix

#499 translate: guide/architecture.md の翻訳
  aio-ja/content/guide/architecture.md
Labels: cla: yes, pr_state: Ready to Merge

#500 translate: guide/aot-compiler.md (#483)
  aio-ja/content/guide/aot-compiler.md
Labels: cla: yes, pr_state: Wait for review

#503 fix(start): set correct code-example region
  aio-ja/content/start/data.md
Labels: cla: yes
