Repository angular/angular-ja, pull requests merged in 2021-06, with the labels that each got.

#660 guide/content-projectionの翻訳 #654
  aio-ja/content/guide/content-projection.en.md
  aio-ja/content/guide/content-projection.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Wait for review

#663 軽微な修正: guide/lifecycle-hooks.md
  aio-ja/content/guide/lifecycle-hooks.md
Labels: cla: yes

#662 guide/dependency-injection-providers.mdの翻訳 #661
  aio-ja/content/guide/dependency-injection-providers.en.md
  aio-ja/content/guide/dependency-injection-providers.md
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Ready to Merge, safe to deploy

#664 build: skip install chromium
  tools/dockerbuild/build.dockerfile
  tools/dockerbuild/watch.dockerfile
Labels: cla: yes, safe to deploy

#668 translate: guide/structural-directives.md
  aio-ja/content/guide/structural-directives.en.md
  aio-ja/content/guide/structural-directives.md
Labels: cla: yes, pr_state: Ready to Merge

#669 [fix] start-data
  aio-ja/content/start/start-data.md
Labels: cla: yes, pr_state: Ready to Merge
