Repository angular/angular-ja, pull requests merged in 2021-02, with the labels that each got.

#610 訂正: navigation.json: サイドバー階層を英語版に合わせる
  aio-ja/content/navigation.json
Labels: cla: yes, pr_state: Ready to Merge

#611 ci: change deploy preview workflow to use a label
  .github/workflows/deploy-preview.yml
Labels: cla: yes, pr_state: Ready to Merge, safe to deploy

#613 fix(aio): disable service worker
  build.sh
  scripts/git-patch/disable-service-worker.patch
Labels: cla: yes, safe to deploy

#616 translate guide/build into Japanese.
  aio-ja/content/guide/build.md
Labels: cla: yes, pr_state: Wait for review, safe to deploy

#612 translated: guide/form-validation.mdの翻訳
  aio-ja/content/guide/form-validation.en.md
  aio-ja/content/guide/form-validation.md
Labels: cla: yes, pr_state: Ready to Merge, safe to deploy

#620 Translate guide/component-overview into japanese
  aio-ja/content/guide/component-overview.en.md
  aio-ja/content/guide/component-overview.md
Labels: cla: yes, pr_state: Ready to Merge, safe to deploy

#621 Translate lifecycle-hooks into Japanese
  aio-ja/content/guide/lifecycle-hooks.md
Labels: cla: yes
