Repository angular/angular-ja, pull requests merged in 2021-07, with the labels that each got.

#673 軽微な修正: guide/glossary.md
  aio-ja/content/guide/glossary.md
Labels: cla: yes, pr_state: Ready to Merge

#674 build: fix zx version to keep Node.js v14 compatibility
  tools/dockerbuild/package.json
Labels: cla: yes

#670 translate: guide/http.md
  aio-ja/content/guide/http.en.md
  aio-ja/content/guide/http.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review
