Repository angular/angular-ja, pull requests merged in 2021-05, with the labels that each got.

#639 docs: Fix typo in tutorial
  aio-ja/content/tutorial/toh-pt0.md
Labels: cla: yes, pr_state: Ready to Merge

#640 translate: guide/component-styles.md
  aio-ja/content/guide/component-styles.md
Labels: cla: yes

#642 chore: remove Netlify badge from README
  README.md
Labels: cla: yes

#643 translate: guide/reactive-forms.md
  aio-ja/content/guide/reactive-forms.md
Labels: cla: yes, pr_state: Ready to Merge, safe to deploy

#644 docs: suggest another translation in tutorial
  aio-ja/content/tutorial/toh-pt4.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review

#637 doc: translate dependency-injection.md
  aio-ja/content/guide/dependency-injection.md
Labels: cla: yes, pr_state: Ready to Merge, pr_state: Wait for review, safe to deploy

#647 feat: search Japanese keyword
  scripts/git-patch/add-japanese-search.patch
Labels: cla: yes, safe to deploy

#651 translate: guide/service-worker-devops.md
  aio-ja/content/guide/service-worker-devops.md
Labels: cla: yes, pr_state: Ready to Merge, pr_state: Wait for review, safe to deploy

#653 軽微な修正: guide/glossary.md
  aio-ja/content/guide/glossary.md
Labels: cla: yes, pr_state: Ready to Merge

#657 環境変数追加(NFS用): chokidarのusePolling
  docker-compose.yml
Labels: cla: yes

#658 軽微な修正: guide/glossary.md
  aio-ja/content/guide/glossary.md
Labels: cla: yes, pr_state: Ready to Merge
