Repository angular/angular-ja, pull requests merged in 2021-04, with the labels that each got.

#628 軽微な修正: start/start-routing.md
  aio-ja/content/start/start-routing.md
Labels: cla: yes, pr_state: Ready to Merge

#629 refactor: create git patch to change document title
  aio-ja/AIO_MODIFY_NOTE.md
  aio-ja/src/app/layout/doc-viewer/doc-viewer.component.ts
  aio-ja/src/index.en.html
  aio-ja/src/index.html
  aio-ja/src/pwa-manifest.json
  build-win.ps1
  build.sh
  scripts/git-patch/change-document-title.patch
Labels: cla: yes, safe to deploy

#630 refactor: add git patch to add Japanese font
  aio-ja/AIO_MODIFY_NOTE.md
  aio-ja/src/styles/_constants.scss
  scripts/git-patch/add-japanese-font.patch
Labels: cla: yes, safe to deploy

#631 refactor: add git patch for translated icon
  aio-ja/src/app/layout/footer/footer.component.html
  aio-ja/src/app/layout/nav-item/nav-item.component.html
  aio-ja/src/app/navigation/navigation.model.ts
  scripts/git-patch/add-translated-icon.patch
Labels: cla: yes, safe to deploy

#632 refactor: add git patch to change analytics id
  aio-ja/AIO_MODIFY_NOTE.md
  aio-ja/src/environments/environment.archive.ts
  aio-ja/src/environments/environment.next.ts
  aio-ja/src/environments/environment.stable.ts
  aio-ja/src/environments/environment.ts
  scripts/git-patch/change-analytics-id.patch
Labels: cla: yes, safe to deploy

#634 translate: guide/what-is-angular.md
  aio-ja/content/guide/what-is-angular.en.md
  aio-ja/content/guide/what-is-angular.md
Labels: cla: yes, pr_state: Need to fix, pr_state: Wait for review, safe to deploy
