Repository angular/angular-ja, pull requests merged in 2022-09, with the labels that each got.

#745 translate: guide/template-reference-variables
  aio-ja/content/guide/template-reference-variables.en.md
  aio-ja/content/guide/template-reference-variables.md
  aio-ja/content/navigation.json
Labels: deploy preview version

#772 translate: DI関連ガイドの翻訳
  aio-ja/content/guide/dependency-injection-overview.en.md
  aio-ja/content/guide/dependency-injection-overview.md
  aio-ja/content/guide/dependency-injection.en.md
  aio-ja/content/guide/dependency-injection.md
  aio-ja/content/guide/dependency-injection.md.old
  aio-ja/content/guide/template-typecheck.md
  aio-ja/content/navigation.json
  prh.yml
Labels: type: translation

#773 translate: DI関連ガイドの翻訳
  aio-ja/content/guide/creating-injectable-service.en.md
  aio-ja/content/guide/creating-injectable-service.md
  aio-ja/content/guide/dependency-injection-providers.en.md
  aio-ja/content/guide/dependency-injection-providers.md
  aio-ja/content/navigation.json
Labels: type: translation

#774 translate: guide/interpolation
  aio-ja/content/guide/interpolation.md
Labels: pr_state: Ready to Merge

#775 translate: guide/image-directive-setup
  aio-ja/content/guide/image-directive-setup.en.md
  aio-ja/content/guide/image-directive-setup.md
Labels: pr_state: Ready to Merge, type: translation

#776 translate: guide/change-detection
  aio-ja/content/guide/change-detection.en.md
  aio-ja/content/guide/change-detection.md
Labels: pr_state: Ready to Merge, type: translation

#777 translate: guide/image-directive
  aio-ja/content/guide/image-directive.en.md
  aio-ja/content/guide/image-directive.md
Labels: pr_state: Ready to Merge, type: translation

#778 translate: guide/devtools
  aio-ja/content/guide/devtools.en.md
  aio-ja/content/guide/devtools.md
Labels: pr_state: Ready to Merge, type: translation

#782 translate: guide/lightweight-injection-tokens
  aio-ja/content/guide/lightweight-injection-tokens.en.md
  aio-ja/content/guide/lightweight-injection-tokens.md
Labels: pr_state: Ready to Merge, type: translation

#781 translate: guide/change-detection-zone-pollution
  aio-ja/content/guide/change-detection-zone-pollution.en.md
  aio-ja/content/guide/change-detection-zone-pollution.md
Labels: pr_state: Ready to Merge, type: translation
