Repository angular/angular-ja, pull requests merged in 2022-10, with the labels that each got.

#785 translate: guide/i18n-common-translation-files
  aio-ja/content/guide/i18n-common-translation-files.en.md
  aio-ja/content/guide/i18n-common-translation-files.md
Labels: pr_state: Ready to Merge

#788 translate: guide/typed-forms
  aio-ja/content/guide/typed-forms.en.md
  aio-ja/content/guide/typed-forms.md
Labels: pr_state: Need to fix, pr_state: Wait for review

#786 translate: guide/change-detection-slow-computations
  aio-ja/content/guide/change-detection-slow-computations.en.md
  aio-ja/content/guide/change-detection-slow-computations.md
Labels: pr_state: Ready to Merge

#784 translate: guide/standalone-components
  aio-ja/content/guide/standalone-components.en.md
  aio-ja/content/guide/standalone-components.md
  aio-ja/content/navigation.json
Labels: pr_state: Ready to Merge, pr_state: Wait for review

#790 translate: guide/change-detection-skipping-subtrees
  aio-ja/content/guide/change-detection-skipping-subtrees.en.md
  aio-ja/content/guide/change-detection-skipping-subtrees.md
Labels: pr_state: Ready to Merge, pr_state: Wait for review
