Repository angular/angular-ja, pull requests merged in 2023-05, with the labels that each got.

#839 translate: guide/i18n-common-merge
  aio-ja/content/guide/i18n-common-merge.en.md
  aio-ja/content/guide/i18n-common-merge.md
Labels: pr_state: Ready to Merge, pr_state: Wait for review

#841 translate: guide/i18n-optional-overview
  aio-ja/content/guide/i18n-optional-overview.en.md
  aio-ja/content/guide/i18n-optional-overview.md
Labels: pr_state: Ready to Merge, pr_state: Wait for review

#844 translate: guide/i18n-optional-manage-marked-text
  aio-ja/content/guide/i18n-optional-manage-marked-text.en.md
  aio-ja/content/guide/i18n-optional-manage-marked-text.md
Labels: pr_state: Ready to Merge

#848 translate: tutorial/first-app
  aio-ja/content/tutorial/first-app/index.en.md
  aio-ja/content/tutorial/first-app/index.md
Labels: pr_state: Wait for review

#850 translate: tutorial/first-app/first-app-lesson-01
  aio-ja/content/tutorial/first-app/first-app-lesson-01.en.md
  aio-ja/content/tutorial/first-app/first-app-lesson-01.md
Labels: pr_state: Wait for review

#853 translate: tutorial/first-app/first-app-lesson-02
  aio-ja/content/tutorial/first-app/first-app-lesson-02.en.md
  aio-ja/content/tutorial/first-app/first-app-lesson-02.md
Labels: pr_state: Wait for review

#859 translate: tutorial/first-app/first-app-lesson-05
  aio-ja/content/tutorial/first-app/first-app-lesson-05.en.md
  aio-ja/content/tutorial/first-app/first-app-lesson-05.md
Labels: pr_state: Wait for review
